spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/note_db
    username: user
    password: pswd

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  #        jdbc:
  #          batch_size: 512
  #        order_inserts: true
  #        order_updates: true
  #        generate_statistics: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${spring.redis.host:localhost}
      port: ${spring.redis.port:6379}
      connection_factory: jedis # `jedis` or `lettuce`

  note:
    default-ttl: 60m
    cache-capacity: 2048

  hashes:
    hash-pool-size: 2000 # must be equals `batch_size`
    pool-exhaustion-percentage: 40 # in percent !!!
    generation-cron: 0 0 */6 * * * # every 6 hours
    generation-thread-pool-size: 4
    hash-cache-size: 500
    cache-exhaustion-percentage: 20 # in percent !!!

  validationRule:
    title-regexp: ^[a-zA-Z0-9].*$
    content-regexp: .*[a-zA-Z0-9].*
    title-length: 128



server:
  port: 8080

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        engine:
          jdbc:
            batch:
              internal:
                BatchingBatch: TRACE